Add endOfMonth function
onebip/onebip-clock pull request #15
Opened 2019-01-24 08:48 UTC by lucacervello

2019-01-24 10:54 UTC, pasquinis requested changes
For me is ok, but look my comments and evaluate it

2019-01-24 10:54 UTC, pasquinis commented on src/Onebip/DateTime/UTCDateTime.php
> +	    $this->toDateTime()->format('Y-m-t')
This `format` is hidden by the name of the function, let a new name of the function reveal it.

2019-01-24 10:54 UTC, pasquinis commented on src/Onebip/DateTime/UTCDateTime.php
> +    public function startOfWeek()
not for all European people the week start with `monday`, be more explicit in the name of the function

2019-01-24 10:54 UTC, pasquinis commented on src/Onebip/DateTime/UTCDateTime.php
> +    public function endOfWeek()
not for all European people the week end with `sunday`, be more explicit in the name of the function

2019-01-24 10:54 UTC, pasquinis commented on spec/unit/Onebip/DateTime/UTCDateTimeTest.php
> +    public function testEndOfMonthWillGiveTheLastDay()
Good coverage

2019-01-25 11:26 UTC, lucacervello commented
@pasquinis new commit, new review. :smiley:

2019-01-28 10:34 UTC, pasquinis approved these changes
Now is good :+1:

2019-01-28 11:01 UTC, merged